### ISSUE TITLE
Add auto-detect feature for KNX routing with multiple network interfaces

### ISSUE THREAD

**Issue by tuxedo0801** [KONNEKTING/KonnektingSuite#13]
subject explains it...

**Comment by tuxedo0801** [comment]
To be tested. beta4-snapshot given to @Adminius for first testing.

**Comment by Adminius** [comment]
it works! :+1:

**Comment by tuxedo0801** [comment]
Works, even if there is a kind of unreliability due to https://github.com/calimero-project/calimero-core/issues/36
