### ISSUE TITLE
Hide parameters and groups

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingSuite#18]
it will be nice to hide not usable parameters depens on other params

xml example:
```XML
<Parameter Id="2">
    <Description>Hide next param</Description>
    <Value Type="uint8" Default="01" Options="00=No|01=Yes|02=Yes, of course" Min="" Max=""/>
</Parameter>

<Parameter Id="3" hideparam="2" hidecompare="ne" hidevalue="00">
    <Description>Hidden parameter</Description>
    <Value Type="uint8" Default="00" Options="00=1|01=2|03=..." Min="" Max=""/>
</Parameter>
````

**Comment by tuxedo0801** [comment]
When having visibility-dependencies between parameters, we should also add visibility-dependency between comobj and parameter to make this feature "complete".
Question is: Is is that "easy" to define dependencies? Or are the more complex dependency-scenarios?

One should extract a ETS product-database (it's a ZIP which contains XML) and have a look who they did it and what kind of scenarios are there available.

**Comment by tuxedo0801** [comment]
Latest findings: 

ETS product database solved it this way:

```XML
<choose ParamRefId="M-0083_A-0014-21-9BC0_P-22_R-33">
    <when test="0">
        <ParameterRefRef RefId="M-0083_A-0014-21-9BC0_UP-24_R-35" />
    </when>
    <when test="1">
        <ParameterRefRef RefId="M-0083_A-0014-21-9BC0_UP-23_R-34" />
        <ParameterRefRef RefId="M-0083_A-0014-21-9BC0_P-5039_R-5039" />
    </when>
</choose>
```

Our latest idea:

Adding a new xml block to "device" xml element:

```XML
<Dependencies>
     <ParameterDependency ParamId="1" Test="eq" TestValue="01"/>
     <CommObjectDependency CommObjId="1" Test="ne" TestParamId="01" TestValue="00" />
</Dependendies>
```

That way, we could setup the suite's UI as before and use the dependencies-element to decide which parameter has to be visible/invisible (depending on another parameter-setting) and which ComObj needs to be visible/invisible based on a parameter-setting.

So we wopuld have backward-compability and it would be easy to integrate it into the UI (changelistener which is fired everytime a parameter changes: iterate over UI elements and enable/disable visibility)

**Comment by tuxedo0801** [comment]
Implementation done. First tests look good. Need to do more tests.

**Comment by tuxedo0801** [comment]
@Masifi @Adminius 
Pls. test. Latest beta4-snapshot is available in our drive folder.

**Comment by tuxedo0801** [comment]
XML Documentation is up2date: https://github.com/KONNEKTING/KonnektingDocumentation/blob/master/konnekting_xml_device_description.md

**Comment by Adminius** [comment]
It works :+1:

**Comment by tuxedo0801** [comment]
Performance has been optimized (save on exit only). Reported from @Adminius  and @Matsifi that it works.

--> Can be closed.
