### ISSUE TITLE
KONNEKTING-CodeCreator messes up Parameters 

### ISSUE THREAD

**Issue by hasselk** [KONNEKTING/KonnektingSuite#20]
tried running the generator with the demosketch xml which has one added comobject

the only param there was created with an added underscode between

this
`    /* Index 0 - blinkDelay */ PARAM_UINT_16}`

instead of this
`    /* Index 0 - blinkDelay */ PARAM_UINT16`

**Comment by tuxedo0801** [comment]
Already fixed this today.
