### ISSUE TITLE
Idea: Parameter for bits in Device XML

### ISSUE THREAD

**Issue by mrniemand** [KONNEKTING/KonnektingSuite#25]
In the moment an config like:
Channel A : init state => activ/not activ
Channel A : central mode => activ / not activ
.....
needs at least 2 parameters. If there are 10 channels you get lot's of parameters.
In the moment you can avoid that by:
Channel A: config => external docoumentation of bit description and calculating byte manuall,y.

=> extend <Parameter> and GUI to handle bit patterns. Maybe:
<Parameter Id="1" Bit="0" .......>
  <Description>hallo</Description>
  <Value Type="bit" ...... />
</Parameter>
<Parameter Id="1" Bit="1" .......>
  <Description>hallo</Description>
  <Value Type="bit" ...... />
</Parameter>

**Comment by tuxedo0801** [comment]
Your're totally right: This is a waste of memory. BUT it keeps the XML simple memory management in the arduino lib and of course also parsing the XML very easy.

Your suggested XML format looks not that bad, but I'm not sure if this can be handled (without tricks) in XSD properly. The suite also needs to be rewritten on same parts to allow multiple parameters with same ID. The whole structure is build on top of the definition "parameters are unique by their ID".

So this would introduce a lot of code changes, to gain what... a few saved bytes on arduino.

Maybe I can work around it and introduce "soft-params", but that would look different to your suggestion, as it would introduce a new xml-element.

**Comment by mrniemand** [comment]
I'm absolutly not fixed to this implementation, just "a little bit more" would be great in that area.
even better for me would be an bit which is part of parameter xx
somthing like:
<Parameter Id="1">
<Bit0>
<Description></Description>
<Value .... / >
</Bit0>
<Bit1>
<Description></Description>
<Value .... / >
</Bit1>
</Parameter>
Yes it saves just a few bytes. But it saves lot's of time, because you don't need to change every id, just because of adding an additional bit.

**Comment by tuxedo0801** [comment]
The suite is mainly for the "end user", not the "developer". Noone said that developers life is easy :-)

I really like to keep the current system and don't add another level of complexity. You're not fixed to the Parameter ID. In your sketch you can use the parameter-id-name. You do not need keep related parameters in same ID range. As the documentation says:

```
You can distribute your parameters in any order over the groups. 
                    Important thing is: 
                        - If you have parameters, there must a parameter with Id="0", 
                        - There are no Id-gaps
```

**Comment by mrniemand** [comment]
of course it's for end users. But try to enlarge the xml without an sorting feature. I tried it, but it looked so confusing that I decided to resort the ids.

**Comment by tuxedo0801** [comment]
It's planned to have a "Developer Tool" that eases creating those XMLs. But it's not yet planned for a specific version.

**Comment by mrniemand** [comment]
good to hear. Unfortunally i didn't use java in the past. Otherwise maybe I could help here. (i use visual studio)

**Comment by tuxedo0801** [comment]
--> Will be solved with developer tool, which is not yet ready.

Closing issue for now.
