### ISSUE TITLE
Idea: DeviceXML: xxxDependency optional Parameter TestParamIdName

### ISSUE THREAD

**Issue by mrniemand** [KONNEKTING/KonnektingSuite#26]
When parameter ids needs to be changed or extended all dependencies might get invalid.
So using the optional parameter IdName of parameters instead of Id could avoid that.
Also it gets better readable:
<CommObjectDependency CommObjId="2" Test="ge" TestParamId="0" TestValue="02"/>
would change to
<CommObjectDependency CommObjId="2" Test="ge" TestParamIdName="button_count" TestValue="02"/>

of course that should be optionally (as the source IdName is also optional)

**Comment by tuxedo0801** [comment]
That will not be changed. ID is "identifier". The **optional** attribute "IdName" is not an ID, it's the corresponding name, that is used by code creator to have a variable name for the parameter.

Device descriptions are not meant to chaneg every week. It's meant to "can be changed" with each device revision. So changing the referencing away from the ID towards a name is not an option.
