### ISSUE TITLE
Not sure if it's a bug / am I blind?: Specific CommObjectDependency check is ignored

### ISSUE THREAD

**Issue by mrniemand** [KONNEKTING/KonnektingSuite#29]
[Taster_v03.txt](https://github.com/KONNEKTING/KonnektingSuite/files/592530/Taster_v03.txt)
I attached the .device.xml as txt, because otherwise github doesn't let me upload it.

I don't know why but it looks as CommObjectDependency for IDs 26,27,28 check is ignored, when TestParamId=7. When I change it to example 4, everything looks good.

**Comment by tuxedo0801** [comment]
Please attach the log-file of suite.

workflow:
* exit suite and remove all KonnektingSuite.log.* log files.
* open the suite (the debug version) and load the xml/reproduce the issue
* exit the suite
* attach the Konnekting.log.0 file to this issue

**Comment by mrniemand** [comment]
[KonnektingSuite.txt](https://github.com/KONNEKTING/KonnektingSuite/files/592734/KonnektingSuite.txt)
I started the suite, selected project directory. Loaded the device XML. Changed Param7, verified the issue in the comobjects list.

**Comment by mrniemand** [comment]
I found the problem myself. IT happend because Parameter Id0 didn't exist. In addition to that also Parameter Id 6 didn't exist. So it looks as made this the suite very unhappy ;)
Maybe you could implement some checking for gaps in the id numbering?

**Comment by tuxedo0801** [comment]
Not a problem. closed
