### ISSUE TITLE
Parameter and Commobj Numeric ID´s should be generated automaticaly

### ISSUE THREAD

**Issue by hasselk** [KONNEKTING/KonnektingSuite#31]
Parameter and Commobj Numeric ID´s should be generated automaticaly  from the order in the xml and not required to be entered using IdName="" that is way more human readable.

Right now if you wanna reorganize or add Parameters/Groups/Commobj to a device its a rather tidious and error prone process. especialy the dependancies are a hell to check

And if you use the IdName in the dependency checks, you dont have to change anything when you add/change stuff.

together with the KONNEKTING CodeCreator this makes life way nicer :-)

**Comment by tuxedo0801** [comment]
IdNames are optional. You can skip the attribute if you like.

It's a design decision that the developer has to spciufy the ID explicitly. So this will not be changed.

As I wrote in another issue: In the future we will have a tool to create the XML so that it will be easier.

**Comment by hasselk** [comment]
Thats sad for me, because it means to easily edit the xml you depend on another tool.

by making IdNames nonOptional and skipping the use of an numeric ID alltogether its easier to edit with whatever editor or IDE you like, you can stay in the same tool without having to switch.
And you cant realy make errors when enumerating the numeric id.
So you only need to use the  KONNEKTING CodeCreator and anything is good. (which can easily be scripted and incorporated in your workflow).
and for the people who want to use the XML Editor tool nothing realy changes.

maybe in the future this design decision might be changed ;)

**Comment by tuxedo0801** [comment]
The parameter and comobj numeric ID is used to identify the value in microcontroller memory. Just generating those IDs would mean, that you can break compatibility. Of course you can  throw away the memory content every time you upgrade the firmware (and that might re-order the genrated IDs completely), but then other people will complain.

So, all in all: It's the developers responsibility to maintain the IDs correctly. 

Once a sketch/firmware is released, it will not be changed completely. Maybe you add further stuff (append IDs to the end of the current list) for a newer version or fix a bug. But the scenario where you steadily change IDs does not exist if you develop your firmware with some planning in background. The more bad your planning is, the more you have to change the IDs...

**Comment by hasselk** [comment]
Thanks for clarification.
Havent thought about memory content in case of an update, but without updates over the bus thats a fairly rare event ;)
Your absolutely right about the planing part.

I havent tested this but can ID´s be in any order i want even over groups given that there are no gaps or will it get confused? would simplify testing when you have new ideas to add...

**Comment by tuxedo0801** [comment]
Yes, that should work. Order or group belonging doesn't matter. Important point is: ID range begins with 0 and there is no gap until end of used IDs.

Update firmware via bus is already planned ;-)

**Comment by hasselk** [comment]
Thanks, that means i can add stuff in and only sort at the end when im satisfied with the function.
That makes testing easier ;)

**Comment by tuxedo0801** [comment]
Exactly. 

Right now, the Suite will sort the order in the parameter-tab by the ID. So you can mix up the IDs over all the parameter groups, but within a group the sorting for display in Suite is done by ID.

In future I might add another attribute for sorting/ordering within a group. SO just keep the current ordering mechanism in mind...
