### ISSUE TITLE
ParameterGroupDependencies mess up UI

### ISSUE THREAD

**Issue by jentz1986** [KONNEKTING/KonnektingSuite#47]
Hi,
I was about to experiment with the Suite in order to build a complex switch from Mats EnOcean Interface.
Environment: Win10 64bit 1709
Konnekting Suite 1.0.0 beta 4 2016-10-10_18-18-18
Notepad++, with XML tools for XSD based validation

XSD-validated XML attached:
[enOceanParametersOnly.kconfig.xml.zip](https://github.com/KONNEKTING/KonnektingSuite/files/1811307/enOceanParametersOnly.kconfig.xml.zip)

Observation:
[StepsToReproduceIssue46.zip](https://github.com/KONNEKTING/KonnektingSuite/files/1811319/StepsToReproduceIssue46.zip)

Recorded using Windows board-tool "psr". .zip-file contains .mht file which can be opened with Internet Explorer. If you encounter issues opening the file, let me know. Then I will extract the screenshots.

**Comment by Adminius** [comment]
solved:
![image](https://user-images.githubusercontent.com/17052262/37406728-25884bee-2798-11e8-90b6-375ba1a34bdf.png)

Value 01 (default) for parameter 04 dosn't exist. change it to right one.
 `<Value Type="uint8" Default="01" Options="0A=200|0B=220|0C=240|0D=260|0E=280|0F=300|10=320|11=340|12=360|13=380|14=400|15=420|16=440"/>`

the same at the bottom (configuration):
`<ParameterConfiguration Id="4" Value="10"/>`

**Comment by jentz1986** [comment]
Wow, thank you! Ouch.
