### ISSUE TITLE
KONNEKTING Suite RS-232 KNX Interface

### ISSUE THREAD

**Issue by Jason0416** [KONNEKTING/KonnektingSuite#55]
Hi, Alex.
First, I tested ABB IPR on KONNEKTING Suite. Everything is ok.
In the second step, using ABB USB-KNX, the Konnekting Suite cannot find the interface. The third step was to test the Busware FT1.2 firmware, Transparent Tpuart, Arduino-style-files (http://busware.de/tiki-index.php?page=TUL). The result was that the interface could not be found.
Alex, which device should I use for the USB-RS232 interface in the KONNEKTING Suite? Only IPR supported?

**Comment by tuxedo0801** [comment]
The Suite currently supports IP Routing, IP tunneling, as well as plain tpuart. As I explained: We have not yet tested busware devices, but I still assume that tpuart firmware should work. Right now I have no clue why it is not working on your side :-( 

You can do your own research on why the Firmware is not 1:1 passing serial commands to KNX transceiver? Maybe there are others having the same issue in a different scenario.

USB KNX Interfaces are not supported and maybe never will get support from us. Reasons are related to driver issues.

**Comment by tuxedo0801** [comment]
just checked their website and the schematics. From my point of view it should work with the tpuart firmware.
Maybe the baudrate is wrong/different?
Di you have docs describing the settings the firmware delivers?

best regards from spain
Alex

**Comment by Jason0416** [comment]
Hi! Alex,
I try the 1:1 passing serial commands use ATMEGA32U4, The KONNEKTING Suite can find serial, But group monitor no any response. If using Arduino serial monitor, The ATMEGA32U4 send, receive is OK.

**Comment by Jason0416** [comment]
ATMEGA32U4 program as:


#include <avr/power.h>

#define LED_BUILTIN A5
#define USBSerial Serial
#define TPUSerial Serial1

int ledState = LOW;     

unsigned long previousMillis = 0;
const long interval = 1000;

void setup() {
  clock_prescale_set(clock_div_1); // required for TUL with factory bootloader
  
  pinMode(LED_BUILTIN, OUTPUT);
  
  USBSerial.begin(19200,SERIAL_8E1);

  while (!USBSerial) {
     ; // wait for serial port to connect. Needed for Leonardo only
  }

  TPUSerial.begin(19200,SERIAL_8E1); // TPU requires EVEN parity!

  /*
  USBSerial.println ("Hit a key to start");     // wait to see initalization
  while(USBSerial.available() == 0){}

  USBSerial.println(F("TUL starting"));
  */
}

void loop() {
  unsigned long currentMillis = millis();

  // serial bridge
   if (USBSerial.available()) {      // If anything comes in Serial (USB),
    TPUSerial.write(USBSerial.read());   // read it and send it out Serial1 (TPU)
    ledState = LOW;  // force LED on
    previousMillis = currentMillis + interval;
  }

  if (TPUSerial.available()) {     // If anything comes in Serial1 (TPU)
    USBSerial.write(TPUSerial.read());   // read it and send it out Serial (USB)
    //USBSerial.print(TPUSerial.read(),HEX);
    ledState = LOW;  // force LED on
    previousMillis = currentMillis + interval;
  } 

  // LED blinking
  if(currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;   
    if (ledState == LOW)
      ledState = HIGH;  // Note that this switches the LED *on*
    else
      ledState = LOW;   // Note that this switches the LED *off*
    digitalWrite(LED_BUILTIN, ledState);
  }

}

**Comment by tuxedo0801** [comment]
Issue solved? If yes, how?
