### ISSUE TITLE
KO tab replaces value of group address if active on device switch

### ISSUE THREAD

**Issue by hasselk** [KONNEKTING/KonnektingSuite#8]
when you doubbleclick on an groupadress Field, and then switch to another device.

the value of ahe active field gets written to the new device, which may be nice if you have no values in it, but else it replaces the existing value

**Comment by tuxedo0801** [comment]
This is indeed an annoying bug. Will fix this for beta3. Thanks for reporting.

**Comment by tuxedo0801** [comment]
fixed. Whenever a cell in ComObject tab is in editing mode and a device selection change happen, the cell editing is stopped before new device is shown.

**Comment by tuxedo0801** [comment]
One more fix left:

if editing cell is not valid (wrong ga format), this fix does not yet work.

**Comment by tuxedo0801** [comment]
cell editing is not stopped, but cancelled. Means: value is NOT applied and any change is lost.
That's the current compromise :-( Might be improved in future versions.
